import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const reportId = searchParams.get('id');

  if (!reportId) {
    return NextResponse.json(
      { error: 'Report ID required' },
      { status: 400 }
    );
  }

  // In production, this would fetch the actual report from backend/storage
  // For demo, we'll generate a mock PDF response
  
  // Mock PDF content
  const mockPdfContent = `Mock Report Content for ${reportId}
Generated at: ${new Date().toISOString()}
Report Type: Risk Analysis
Client: Demo Client

Risk Summary:
- High Risk Clients: 12
- Medium Risk Clients: 45
- Low Risk Clients: 143

This is a demo report. In production, this would be a real PDF generated by your backend.`;

  return new NextResponse(mockPdfContent, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="report-${reportId}.pdf"`,
    },
  });
}